### ISSUE TITLE
premium storage and tables

### ISSUE THREAD

**Issue by pronoiac** [cloudfoundry-incubator/bosh-azure-cpi-release#117]
we are trying to use premium storage for everything, so default storage account is premium. it looks like tables do not work in premium storage accounts.

thoughts?

```
  Started creating missing vms > ha_proxy_z1/0 (feabf4e3-cc22-4e44-a1fb-e47a45f2df17). Failed: has_table?: #<Faraday::ConnectionFailed>
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/resolv-replace.rb:12:in `rescue in getaddress'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/resolv-replace.rb:9:in `getaddress'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/resolv-replace.rb:23:in `initialize'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/net/http.rb:879:in `open'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/net/http.rb:878:in `connect'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/net/http.rb:852:in `start'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/net/http.rb:1369:in `request'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/net/http.rb:1128:in `get'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:76:in `perform_with_redirection'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:64:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/azure-0.7.1/lib/azure/core/http/http_request.rb:143:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/azure-0.7.1/lib/azure/core/http/signer_filter.rb:28:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/azure-0.7.1/lib/azure/core/http/signer_filter.rb:28:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/azure-0.7.1/lib/azure/core/http/http_request.rb:97:in `block in with_filter'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/azure-0.7.1/lib/azure/core/service.rb:36:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/azure-0.7.1/lib/azure/core/filtered_service.rb:34:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/azure-0.7.1/lib/azure/core/signed_service.rb:41:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/azure-0.7.1/lib/azure/table/table_service.rb:97:in `get_table'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/table_manager.rb:22:in `has_table?'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/stemcell_manager.rb:93:in `handle_stemcell_in_different_storage_account'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/stemcell_manager.rb:69:in `has_stemcell?'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:91:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_common-1.3100.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:83:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3100.0/lib/bosh/cpi/cli.rb:71:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3100.0/lib/bosh/cpi/cli.rb:71:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:34:in `<main>' (00:00:08)
```

**Comment by pronoiac** [comment]
cc @cppforlife

**Comment by AbelHu** [comment]
@pronoiac Please use Azure DNS 168.63.129.16 and try it again.

**Comment by cppforlife** [comment]
can you confirm that using tables with premium storage is supported? we cant find tables button in the portal. it does appear for non-prem storage. also running cli results in cryptic error (status code on http response is not found) when trying to create table on prem stor acct.

**Comment by AbelHu** [comment]
@cppforlife We will investigate it and update you later.

**Comment by AbelHu** [comment]
@pronoiac @cppforlife Currently you only can choose standard storage account as the default storage account.

Premium Page Blob: Premium Storage supports Azure Page Blobs, which are used to hold persistent disks for Azure Virtual Machines (VMs). Currently, Premium Storage **does not support** Azure Block Blobs, Azure Append Blobs, Azure Files, **Azure Tables**, or Azure Queues.
Reference: https://azure.microsoft.com/en-us/documentation/articles/storage-premium-storage/

**Comment by AbelHu** [comment]
@pronoiac If you want to use premium storage account for BOSH, you can set storage_account_name to your premium storage account name in resource_pools in bosh.yml. BOSH os disk and data disks will be created in the premium storage account.
