### ISSUE TITLE
delete vm does not seem to properly clean up network interfaces

### ISSUE THREAD

**Issue by pronoiac** [cloudfoundry-incubator/bosh-azure-cpi-release#121]
```
Error 100: #<Bosh::AzureCloud::AzureError: http_put - error: 400 message: {
  "error": {
    "code": "PrivateIPAddressInUse",
    "message": "IP configuration /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/networkInterfaces/xxx/ipConfigurations/ipconfig1 is using the same private IP address 10.10.16.57 as IP configuration /subscriptions/xxx/resourceGroups/titletest-resource/providers/Microsoft.Network/networkInterfaces/xxx/ipConfigurations/ipconfig1.",
    "details": []
  }
}>
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:937:in `check_completion'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1020:in `http_put'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:632:in `create_network_interface'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb:52:in `create'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:95:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_common-1.3100.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:83:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3100.0/lib/bosh/cpi/cli.rb:71:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3100.0/lib/bosh/cpi/cli.rb:71:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:34:in `<main>'
```

should delete vm be more careful about cleaning up network interfaces?

**Comment by AbelHu** [comment]
@pronoiac It seems like that the previous deployment fails so that the network interface with the same IP exists. Could you provide the full log including the log previous failed task which could not delete the network interface to me chou.hu@microsoft.com?

**Comment by pronoiac** [comment]
Hey, I think the problem happened while using version 6 of the cpi. I'll use a newer version and I'll reach out if it recurs, but I'm closing this for now.
