### ISSUE TITLE
CPI should retry `connect` calls

### ISSUE THREAD

**Issue by cppforlife** [cloudfoundry-incubator/bosh-azure-cpi-release#132]
Since connection was not yet established it should be safe to retry connect calls.

```
\External CPI got response: {"result":null,"error":{"type":"Unknown","message":"Connection timed out - connect(2) for \"some-ip-address\" port 443","ok_to_retry":false},"log":"Rescued Unknown: Connection timed out - connect(2) for \"some-ip-address\" port 443. backtrace: /var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/resolv-replace.rb:23:in `initialize'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/resolv-replace.rb:23:in `initialize'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/net/http.rb:879:in `open'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/net/http.rb:878:in `connect'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/net/http.rb:852:in `start'
/var/vcap/packages/ruby_azure_cpi/lib/ruby/2.1.0/net/http.rb:1369:in `request'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:76:in `perform_with_redirection'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:64:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/azure-core-0.1.1/lib/azure/core/http/http_request.rb:145:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/azure-core-0.1.1/lib/azure/core/http/signer_filter.rb:28:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/azure-core-0.1.1/lib/azure/core/http/signer_filter.rb:28:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/azure-core-0.1.1/lib/azure/core/http/http_request.rb:99:in `block in with_filter'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/azure-core-0.1.1/lib/azure/core/service.rb:36:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/azure-core-0.1.1/lib/azure/core/filtered_service.rb:34:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/azure-core-0.1.1/lib/azure/core/signed_service.rb:41:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/azure-0.7.4/lib/azure/blob/blob_service.rb:1385:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/azure-0.7.4/lib/azure/blob/blob_service.rb:785:in `get_blob_properties'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb:148:in `block in copy_blob'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb:327:in `block in initialize_blob_client'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb:319:in `synchronize'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb:319:in `initialize_blob_client'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb:139:in `copy_blob'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/stemcell_manager.rb:121:in `handle_stemcell_in_different_storage_account'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/stemcell_manager.rb:69:in `has_stemcell?'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:97:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_common-1.3215.4.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:84:in `create_vm'
```

**Comment by AbelHu** [comment]
I am discussing the retry logic with Azure Ruby team. It may be better to add retry in SDK level.
https://github.com/Azure/azure-storage-ruby/issues/18

**Comment by AbelHu** [comment]
CPI has switched from azure-sdk-for-ruby to azure-storage-ruby. Now CPI has enabled [retry](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/ab3acdf871734f2132acf963ba9291b716a10fd2/src/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb#L293) to access Azure storage.
