### ISSUE TITLE
Orphaned network cards

### ISSUE THREAD

**Issue by OlegGerber** [cloudfoundry-incubator/bosh-azure-cpi-release#366]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 32
BOSH     Version: "264.4.0"

### Stemcell
Version: 3468.16
Distro:
  - [x] Ubuntu

### Environment
- Azure Environment:
  - [x] Azure

### Issue Details
Orphaned network cards remain in the resource groups after the deployment job failures due to the disk/cpu quota issues during the VM creation.
 VM it self successfully terminating however the network card which was created as part of this deployment remain in place and causes to the conflicts for future deployments.

**Comment by gossion** [comment]
Hi @OlegGerber,
 CPI has the logic to delete the network cards if it fails to create a VM, please see it in the [source code](https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/v32/src/bosh_azure_cpi/lib/cloud/azure/vm_manager.rb#L148-L153).

For your case, I guess Azure failed to delete the network card. You might be able to find related error about deleting network card in bosh debug log. We will be happy to check if you can send the debug log to us at azcfengg@microsoft.com.

In order to mitigate your issue and go ahead to future deployments, you need to manually delete the network card and the dynamic public IP if it exists (these two resources have the similar name: UUID-0 for network card; UUID for dynamic public IP).

**Comment by gossion** [comment]
Hi @OlegGerber , can you send the debug log to us (azcfengg@microsoft.com), we would like to check
1. why it failed to delete NIC
1. did the retry policy work on deleting NIC

Thanks

**Comment by bingosummer** [comment]
Ping @OlegGerber

**Comment by bingosummer** [comment]
Closing as stale, feel free to mention us and have it re-opened.

**Comment by jsievers** [comment]
this is still happening for us with CPI version 39.0.0 and bosh 271.16.0 

I will attach the bosh debug logs

**Comment by jsievers** [comment]
[bosh_debug_log.txt](https://github.com/cloudfoundry/bosh-azure-cpi-release/files/9028385/bosh_debug_log.txt)


can we re-open?

**Comment by jsievers** [comment]
according to
https://github.com/cloudfoundry/bosh-azure-cpi-release/blob/5d1f38bae0e18b693d7af0edd40b1519647e7595/src/bosh_azure_cpi/lib/cloud/azure/restapi/azure_client.rb#L2344

it's not retrying to delete the NIC because HTTP 409 is not in AZURE_GENERAL_RETRYABLE_ERROR_CODES

but it should be retrying at least for 180 seconds as the error message says

```

D, [2022-07-01T01:55:28.032493 #4457] [create_missing_vm(azure-cf-eu20-integrate-c9854865d83a94a18bfcfa66a1ce9ca23-cassandra/cf593bb6-c5e1-4ccd-a318-3cf86f73e72e (2)/3)] DEBUG -- DirectorJobRunner: [external-cpi] [cpi-740194] response: {"result":null,"error":{"type":"Bosh::Clouds::VMCreationFailed","message":"The VM fails in creating but an error is thrown in cleanuping network interfaces or dynamic public IP.\\n#<Bosh::AzureCloud::AzureError: http_delete - http code: 400\nx-ms-client-request-id: b15562a7-b758-43d8-99b2-2e3b8bce2b85\nx-ms-request-id: 947e7b7e-427c-4f9a-a0c7-5fae2864ef0d\nx-ms-correlation-request-id: 79baaf7d-b1eb-4b1e-8e65-50d8f7d0cee5\nx-ms-routing-request-id: WESTEUROPE:20220701T015527Z:79baaf7d-b1eb-4b1e-8e65-50d8f7d0cee5\nError message: {\r\n  \"error\": {\r\n    \"code\": \"NicReservedForAnotherVm\",\r\n    \"message\": \"Nic(s) in request is reserved for another Virtual Machine for 180 seconds. Please provide another nic(s) or retry after 180 seconds. Reserved VM: /subscriptions/ac0161b0-b900-4b09-a8aa-b54851f51e7b/resourceGroups/azure-cf-eu20-integrate-resource-group/providers/Microsoft.Compute/virtualMachines/319346b4-76a2-4de2-8290-649b25741c23\",\r\n    \"details\": []\r\n  }\r\n}>\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/lib/cloud/azure/restapi/azure_client.rb:2454:in `check_completion'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/lib/cloud/azure/restapi/azure_client.rb:2599:in `http_delete'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/lib/cloud/azure/restapi/azure_client.rb:1553:in `delete_network_interface'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/lib/cloud/azure/vms/vm_manager.rb:243:in `block (2 levels) in create'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/lib/cloud/azure/vms/vm_manager.rb:242:in `each'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/lib/cloud/azure/vms/vm_manager.rb:242:in `block in create'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `block in synchronize'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:19:in `execute'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/ivar.rb:169:in `safe_execute'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/future.rb:55:in `block in execute'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/vendor/bundle/ruby/3.1.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'\n/var/vcap/data/packages/bosh_azure_cpi/d35bb9f64e73348852769de2c34b9e4b79d4e13c/vendor/bundle/ruby/3.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'#<Bosh::AzureCloud::AzureConflictError: http_put - http code: 409\nx-ms-client-request-id: edddff68-bbc6-4614-9dcf-ee17aec4fbd3\nx-ms-request-id: 16fb5dba-7a38-4af2-b1f3-38d705f36dec\nx-ms-correlation-request-id: 5f778c27-fd04-4242-b63e-28981358acaf\nx-ms-routing-request-id: WESTEUROPE:20220701T015526Z:5f778c27-fd04-4242-b63e-28981358acaf\nError message: {\r\n  \"error\": {\r\n    \"code\": \"OperationNotAllowed\",\r\n    \"message\": \"Operation could not be completed as it results in exceeding approved standardDSv3Family Cores quota.
```
