### ISSUE TITLE
VM is not created because of availabilitySet is missing

### ISSUE THREAD

**Issue by gossion** [cloudfoundry-incubator/bosh-azure-cpi-release#528]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: dev
BOSH     Version:
CF       Version:
Diego    Version:

### Stemcell
Version:
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [x] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [ ] AzureStack
    - Version: (e.g. 1712 update or build number 180106.1)
  - [ ] Others:
- Location: (e.g. East US)
- Subscription ID:
- Resource Group Name:
- [ ] Use Managed Disks

### Logs (*Please redact all sensitive information in your logs*)
Task 94 | 05:33:51 | Preparing deployment: Preparing deployment (00:00:01)
Task 94 | 05:33:52 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 94 | 05:33:52 | Compiling packages: nginx/23c0391f6bb6630cf68ba02c99f93eabdd65839d (00:13:00)
                   L Error: CPI error 'Bosh::Clouds::VMCreationFailed' with message '#<Bosh::AzureCloud::AzureNotFoundError: http_put - http code: 404
x-ms-client-request-id: c9ab369b-c95e-4a2c-aa32-72aff99e853d
x-ms-request-id: 1b750201-6a8e-49b5-9db0-6ebb96455507
x-ms-correlation-request-id: ee60bc5e-59d8-439a-8cfc-20f2d0f54ecc
x-ms-routing-request-id: SOUTHEASTASIA:20180913T054641Z:ee60bc5e-59d8-439a-8cfc-20f2d0f54ecc
Error message: {
  "error": {
    "code": "NotFound",
    "message": "The Availability Set '/subscriptions/c4528d9e-c99a-48bb-b12d-fde2176a43b8/resourceGroups/guwe0628/providers/Microsoft.Compute/availabilitySets/azure-nginx-compilation-2ffd3651-1798-4141-a893-2b421b6d4025' cannot be found.
"
  }
}>
/var/vcap/data/packages/bosh_azure_cpi/28081d2908b122b1288f09ebb46537e4aa6c79a9/lib/cloud/azure/restapi/azure_client.rb:2308:in `check_completion'
/var/vcap/data/packages/bosh_azure_cpi/28081d2908b122b1288f09ebb46537e4aa6c79a9/lib/cloud/azure/restapi/azure_client.rb:2397:in `http_put'
/var/vcap/data/packages/bosh_azure_cpi/28081d2908b122b1288f09ebb46537e4aa6c79a9/lib/cloud/azure/restapi/azure_client.rb:405:in `create_virtual_machine'
/var/vcap/data/packages/bosh_azure_cpi/28081d2908b122b1288f09ebb46537e4aa6c79a9/lib/cloud/azure/vms/vm_manager.rb:446:in `block in _create_virtual_machine'
/var/vcap/data/packages/bosh_azure_cpi/28081d2908b122b1288f09ebb46537e4aa6c79a9/lib/cloud/azure/utils/helpers.rb:563:in `flock'
/var/vcap/data/packages/bosh_azure_cpi/28081d2908b122b1288f09ebb46537e4aa6c79a9/lib/cloud/azure/vms/vm_manager.rb:445:in `_create_virtual_machine'
/var/vcap/data/packages/bosh_azure_cpi/28081d2908b122b1288f09ebb46537e4aa6c79a9/lib/cloud/azure/vms/vm_manager.rb:148:in `create'
/var/vcap/data/packages/bosh_azure_cpi/28081d2908b122b1288f09ebb46537e4aa6c79a9/lib/cloud/azure/cloud.rb:184:in `block (2 levels) in create_vm'
/var/vcap/data/packages/bosh_azure_cpi/28081d2908b122b1288f09ebb46537e4aa6c79a9/lib/cloud/azure/telemetry/telemetry_manager.rb:43:in `monitor'
/var/vcap/data/packages/bosh_azure_cpi/28081d2908b122b1288f09ebb46537e4aa6c79a9/lib/cloud/azure/cloud.rb:164:in `block in create_vm'
/var/vcap/data/packages/bosh_azure_cpi/28081d2908b122b1288f09ebb46537e4aa6c79a9/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/data/packages/bosh_azure_cpi/28081d2908b122b1288f09ebb46537e4aa6c79a9/lib/cloud/azure/cloud.rb:159:in `create_vm'
/var/vcap/data/packages/bosh_azure_cpi/28081d2908b122b1288f09ebb46537e4aa6c79a9/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `public_send'
/var/vcap/data/packages/bosh_azure_cpi/28081d2908b122b1288f09ebb46537e4aa6c79a9/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:39:in `<top (required)>'
/var/vcap/data/packages/ruby-2.4-r4/d5ebccf11ec42fc3ad13edad887caf1d5723dac5/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
/var/vcap/data/packages/ruby-2.4-r4/d5ebccf11ec42fc3ad13edad887caf1d5723dac5/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
/var/vcap/data/packages/ruby-2.4-r4/d5ebccf11ec42fc3ad13edad887caf1d5723dac5/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
/var/vcap/data/packages/ruby-2.4-r4/d5ebccf11ec42fc3ad13edad887caf1d5723dac5/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
/var/vcap/data/packages/ruby-2.4-r4/d5ebccf11ec42fc3ad13edad887caf1d5723dac5/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/data/packages/ruby-2.4-r4/d5ebccf11ec42fc3ad13edad887caf1d5723dac5/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/data/packages/ruby-2.4-r4/d5ebccf11ec42fc3ad13edad887caf1d5723dac5/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/d5ebccf11ec42fc3ad13edad887caf1d5723dac5/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
/var/vcap/data/packages/ruby-2.4-r4/d5ebccf11ec42fc3ad13edad887caf1d5723dac5/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/data/packages/ruby-2.4-r4/d5ebccf11ec42fc3ad13edad887caf1d5723dac5/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:30:in `block in <main>'
/var/vcap/data/packages/ruby-2.4-r4/d5ebccf11ec42fc3ad13edad887caf1d5723dac5/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/var/vcap/packages/ruby-2.4-r4/bin/bundle:22:in `<main>'' in 'create_vm' CPI method

**Comment by gossion** [comment]
Debug info:

Failed to create VM at the 1st time
```
D, [2018-09-13T05:35:21.914258 #12132 #47394859544400] DEBUG -- [req_id cpi-778559]: check_completion - InProgress...
D, [2018-09-13T05:35:51.914532 #12132 #47394859544400] DEBUG -- [req_id cpi-778559]: check_completion - trying to get the status of asynchronous operation: https://management.azure.com/subscriptions/c4528d9e-c99a-48bb-b12d-fde2176a43b8/providers/Microsoft.Compute/locations/southeastasia/operations/36dfe49f-835d-4423-b41f-a4fdf4200884?api-version=2016-04-30-preview
D, [2018-09-13T05:35:51.914865 #12132 #47394859544400] DEBUG -- [req_id cpi-778559]: http_get_response - 0: GET, x-ms-client-request-id: b0b78f7d-6519-4056-9cdd-09a9d3cb4dd2, URI: https://management.azure.com/subscriptions/c4528d9e-c99a-48bb-b12d-fde2176a43b8/providers/Microsoft.Compute/locations/southeastasia/operations/36dfe49f-835d-4423-b41f-a4fdf4200884?api-version=2016-04-30-preview
D, [2018-09-13T05:35:51.993123 #12132 #47394859544400] DEBUG -- [req_id cpi-778559]: http_get_response - 200
x-ms-client-request-id: b0b78f7d-6519-4056-9cdd-09a9d3cb4dd2
x-ms-request-id: d3e6c979-9936-49b4-bbd5-511f2e03ce31
x-ms-correlation-request-id: 4c759cb0-7a81-454f-8906-3e80d20e43dd
x-ms-routing-request-id: SOUTHEASTASIA:20180913T053551Z:4c759cb0-7a81-454f-8906-3e80d20e43dd
response.body: {"startTime":"2018-09-13T05:34:10.2455292+00:00","endTime":"2018-09-13T05:35:27.0372592+00:00","status":"Failed","error":{"code":"OSProvisioningInternalError","message":"OS Provisioning failed for VM '7daebca5-8cf6-4a5a-8ec7-3470fb542176' due to an internal error."},"name":"36dfe49f-835d-4423-b41f-a4fdf4200884"}
W, [2018-09-13T05:35:51.993395 #12132 #47394859544400] WARN -- [req_id cpi-778559]: check_completion - http_put fails for an AzureAsynInternalError. Will retry after 480 seconds.
...
x-ms-routing-request-id: SOUTHEASTASIA:20180913T054411Z:631d2cb8-7ffa-4a7a-b4d6-3c6ee4b6a7b7
response.body: {"startTime":"2018-09-13T05:43:52.4341527+00:00","endTime":"2018-09-13T05:44:08.9500738+00:00","status":"Failed","error":{"code":"OSProvisioningClientError","message":"OS Provisioning failure has reached terminal state and is non-recoverable for VM '7daebca5-8cf6-4a5a-8ec7-3470fb542176'. Consider deleting and recreating this virtual machine. Also, make sure the image has been properly prepared (generalized).\r\n * Instructions for Windows: https://azure.microsoft.com/documentation/articles/virtual-machines-windows-upload-image/ \r\n * Instructions for Linux: https://azure.microsoft.com/documentation/articles/virtual-machines-linux-capture-image/. \r\n \r\nAdditional Details: OS Provisioning failed for VM '7daebca5-8cf6-4a5a-8ec7-3470fb542176' due to an internal error."},"name":"4ef6e930-187e-4853-9192-cbacf39db492"}
```

It deleted VM AND availability set
```
D, [2018-09-13T05:46:29.629230 #12132 #47394859544400] DEBUG -- [req_id cpi-778559]: delete_availability_set - trying to delete 'azure-nginx-compilation-2ffd3651-1798-4141-a893-2b421b6d4025' from resource group 'guwe0628'
I, [2018-09-13T05:46:29.629467 #12132 #47394859544400] INFO -- [req_id cpi-778559]: http_delete - 0: trying to delete https://management.azure.com//subscriptions/c4528d9e-c99a-48bb-b12d-fde2176a43b8/resourceGroups/guwe0628/providers/Microsoft.Compute/availabilitySets/azure-nginx-compilation-2ffd3651-1798-4141-a893-2b421b6d4025?api-version=2016-04-30-preview
```

Later on, it tried to create the VM again. But this time the availabilitySet is already deleted.
```
I, [2018-09-13T05:46:40.947548 #12132 #47394859544400] INFO -- [req_id cpi-778559]: http_put - 0: trying to put https://management.azure.com//subscriptions/c4528d9e-c99a-48bb-b12d-fde2176a43b8/resourceGroups/guwe0628/providers/Microsoft.Compute/virtualMachines/7daebca5-8cf6-4a5a-8ec7-3470fb542176?validating=true&api-version=2016-04-30-preview
```

So the conclusion is, CPI should not delete empty availabilitySet before before retry on creating VM.

**Comment by gossion** [comment]
#530
