### ISSUE TITLE
Following guidance docs, fails uploading stemcell

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry-incubator/bosh-azure-cpi-release#65]
I got to this doc: https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/get-started/deploy-bosh-using-arm-templates.md

And deployed my dev box by clicking the button.  I left `tenantID` as `TENANT-ID` and `clientID` as `CLIENT-ID`, and set `clientSecret` to some new secret I made up.  The dev box provisioned fine, and then I tried to run `./deploy_bosh.sh`.  I did not update `~/bosh.yml` because it's not clear what values I need to change, and what they should be changed to.

The error I'm seeing is:

```
agupta@devbox:~$ ./deploy_bosh.sh
Deployment manifest: '/home/agupta/bosh.yml'
Deployment state: '/home/agupta/bosh-state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:03)
  Downloading release 'bosh-azure-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-azure-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:21)
Finished validating (00:00:26)

Started installing CPI
  Compiling package 'ruby_azure_cpi/3db71123fb72f5ec81955710b2e89e2cbbd8aca0'... Finished (00:00:00)
  Compiling package 'bosh_azure_cpi/5985e1e82c78fadb5f2c951f319012403ee04fd8'... Finished (00:00:00)
  Installing packages... Finished (00:00:11)
  Rendering job templates... Finished (00:00:03)
  Installing job 'cpi'... Finished (00:00:00)
Finished installing CPI (00:00:15)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-azure-hyperv-ubuntu-trusty-go_agent/0000'... Failed (00:00:01)
Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Command 'deploy' failed:
  creating stemcell (bosh-azure-hyperv-ubuntu-trusty-go_agent 0000):
    CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::Clouds::CloudError","message":"http_get_response - get_token - http error: 400\n/home/agupta/.bosh_init/installations/2a344a15-6309-449a-5e8c-266083aa014f/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:842:in `get_token'\n/home/agupta/.bosh_init/installations/2a344a15-6309-449a-5e8c-266083aa014f/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:861:in `http_get_response'\n/home/agupta/.bosh_init/installations/2a344a15-6309-449a-5e8c-266083aa014f/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:1013:in `http_post'\n/home/agupta/.bosh_init/installations/2a344a15-6309-449a-5e8c-266083aa014f/packages/bosh_azure_cpi/lib/cloud/azure/azure_client2.rb:792:in `get_storage_account_keys_by_name'\n/home/agupta/.bosh_init/installations/2a344a15-6309-449a-5e8c-266083aa014f/packages/bosh_azure_cpi/lib/cloud/azure/table_manager.rb:13:in `initialize'\n/home/agupta/.bosh_init/installations/2a344a15-6309-449a-5e8c-266083aa014f/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:367:in `new'\n/home/agupta/.bosh_init/installations/2a344a15-6309-449a-5e8c-266083aa014f/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:367:in `init_azure'\n/home/agupta/.bosh_init/installations/2a344a15-6309-449a-5e8c-266083aa014f/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:19:in `initialize'\n/home/agupta/.bosh_init/installations/2a344a15-6309-449a-5e8c-266083aa014f/packages/bosh_azure_cpi/bin/azure_cpi:26:in `new'\n/home/agupta/.bosh_init/installations/2a344a15-6309-449a-5e8c-266083aa014f/packages/bosh_azure_cpi/bin/azure_cpi:26:in `block in \u003cmain\u003e'\n/home/agupta/.bosh_init/installations/2a344a15-6309-449a-5e8c-266083aa014f/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3100.0/lib/bosh/cpi/cli.rb:70:in `call'\n/home/agupta/.bosh_init/installations/2a344a15-6309-449a-5e8c-266083aa014f/packages/bosh_azure_cpi/vendor/bundle/ruby/2.1.0/gems/bosh_cpi-1.3100.0/lib/bosh/cpi/cli.rb:70:in `run'\n/home/agupta/.bosh_init/installations/2a344a15-6309-449a-5e8c-266083aa014f/packages/bosh_azure_cpi/bin/azure_cpi:34:in `\u003cmain\u003e'","ok_to_retry":false}
```

When I look at `run.log`, I see:

```
[Cmd Runner] 2015/12/25 01:49:18 DEBUG - Stderr: I, [2015-12-25T01:49:17.892396 #61489]  INFO -- : http_post - trying to post https://management.azure.com//subscriptions/<REDACTED>/resourceGroups/<REDACTED>/providers/Microsoft.Storage/storageAccounts/<REDACTED>/listKeys?api-version=2015-05-01-preview
I, [2015-12-25T01:49:17.892683 #61489]  INFO -- : get_token - trying to get/refresh Azure authentication token
E, [2015-12-25T01:49:18.064396 #61489] ERROR -- : http_get_response - get_token - http error: 400
```

When I try to curl the URL, I get a `401` error because I'm not setting the Authorization headers, which makes sense.  But the deploy is getting `400`, so I assume it's setting the Authorization headers fine, and there's something else malformed about the request, but I don't know what it is, and can't see the request payload in any log output.

I wouldn't be surprised if my `bosh.yml` manifest needs some values changed, but I don't know what would need to be changed.  The docs say:

> If you leave TENANT-ID, CLIENT-ID, CLIENT-SECRET at default values in section 1, you need to update these three properties in ~/bosh.yml.

But update the values to what?

**Comment by AbelHu** [comment]
You need to create a service principle by following this [guide] (https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/get-started/create-service-principal.md). Then you need to update those three parameters in bosh.yml. And you also need to do below manual steps by following the [guide] (https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/blob/master/docs/get-started/deploy-bosh-manually.md).
1.2.3 Create Containers
1.2.4 Create Tables

**Comment by Amit-PivotalLabs** [comment]
Thanks, I had done the service principal step already, but the documentation didn't make it clear what values for CLIENT-ID, etc. I was supposed to fill in those forms.  I also never noted down my CLIENT-ID so I had to do `azure ad sp list` and find the one corresponding to the input I gave to the command when I ran `azure ad create app`.  Seems to be working now, thanks.

**Comment by Amit-PivotalLabs** [comment]
@AbelHu I'm not deploying on BOSH manually, so would I still need to do those manual steps of creating tables/containers?

**Comment by AbelHu** [comment]
@Amit-PivotalLabs I have checked the steps. You can skip it because the template has used storage account/key to create containers and tables automatically.
